spring:

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: dw        # 너가 설정한 계정
    password: 1234      # 너가 설정한 비밀번호

  h2:
    console:
      enabled: true
      path: /h2-console   # 접속 주소: http://localhost:8080/h2-console

  jpa:
    defer-datasource-initialization: true   # data.sql 실행 보장
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always   # ★ data.sql 자동 실행되게 하는 핵심 옵션
